In [2]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score

In [3]:
df = pd.read_csv("C:/Users/vedan/Sem 1 SET/cleaned_dataset_final4.csv")

In [4]:
df

Score                             Summary  \
0           5               Good Quality Dog Food   
1           1                   Not as Advertised   
2           4               "Delight" says it all   
3           2                      Cough Medicine   
4           5                         Great taffy   
...       ...                                 ...   
525809      5                 Will not do without   
525810      2                        disappointed   
525811      5            Perfect for our maltipoo   
525812      5  Favorite Training and reward treat   
525813      5                         Great Honey   

                                                     Text  \
0       I have bought several of the Vitality canned d...   
1       Product arrived labeled as Jumbo Salted Peanut...   
2       This is a confection that has been around a fe...   
3       If you are looking for the secret ingredient i...   
4       Great taffy at a great price.  There was a wid...   
...                                                   ...   
525809  Great for sesame chicken..this is a good if no...   
525810  I'm disappointed with the flavor. The chocolat...   
525811  These stars are small, so you can give 10-15 o...   
525812  These are the BEST treats for training and rew...   
525813  I am very satisfied ,product is as advertised,...   

                                                final_rev  Label  
0       bought several vitality canned dog food produc...      1  
1       product arrived labeled jumbo salted peanutsth...      0  
2       confection around century light pillowy citrus...      1  
3       looking secret ingredient robitussin believe f...      0  
4       great taffy great price wide assortment yummy ...      1  
...                                                   ...    ...  
525809  great sesame chickenthis good better resturant...      1  
525810  im disappointed flavor chocolate note especial...      0  
525811  star small give 1015 one training session trie...      1  
525812  best treat training rewarding dog good groomin...      1  
525813  satisfied product advertised use cereal raw vi...      1  

[525814 rows x 5 columns]

In [30]:
df[:1]

Score                Summary  \
0      5  Good Quality Dog Food   

                                                Text  \
0  I have bought several of the Vitality canned d...   

                                           final_rev  Label  
0  bought several vitality canned dog food produc...      1

In [41]:
X_train, X_test, y_train, y_test = train_test_split(df["final_rev"], df["Label"])

In [42]:
vect = TfidfVectorizer().fit(X_train)

In [43]:
len(vect.get_feature_names())

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


186353

In [44]:
X_train_vectorized = vect.transform(X_train)

In [45]:
model = MultinomialNB()

In [46]:
model.fit(X_train_vectorized,y_train)

MultinomialNB()

In [47]:
predictions = model.predict(vect.transform(X_test))

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,recall_score,precision_score

In [48]:
nb_report = accuracy_score(y_test,predictions)
print('Accuracy:',nb_report)

Accuracy: 0.8559572169732378


In [62]:
report3=precision_score(y_test,predictions)
print(report3)

0.8543387156415629


In [49]:
nb_report1 = recall_score(y_test,predictions,average='binary')
print('Recall:',nb_report1)

Recall: 0.9997565966806999


In [50]:
test_review = vect.transform(["This  is very bad}"])
model.predict(test_review)

array([1], dtype=int64)

In [51]:
test_review2 = vect.transform(["I love this product"])
print(model.predict(test_review2))
print(model.predict_proba(test_review2))

[1]
[[0.05480119 0.94519881]]


In [52]:
metrics.confusion_matrix(y_test,predictions)

array([[  1619,  18908],
       [    27, 110900]], dtype=int64)

In [60]:
from sklearn import metrics

In [19]:
feature_names = np.array(vect.get_feature_names())

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [20]:
sorted_coef_index = model.coef_[0].argsort()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:103: FutureWarning: Attribute `coef_` was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


In [55]:
model.predict_proba(vect.transform(['product arrived labeled jumbo salted peanutsthe peanut actually small sized unsalted sure error vendor intended represent product jumbo']))

array([[0.20733349, 0.79266651]])

In [34]:
y_test.value_counts()

1    110912
0     20542
Name: Label, dtype: int64

In [56]:
y_test.value_counts()

1    110927
0     20527
Name: Label, dtype: int64

In [36]:
(20542/110912)*100

18.52098961338719

In [40]:
df['Label'].value_counts()

1    443777
0     82037
Name: Label, dtype: int64